export const db =[
    {   
        id:'1',
        awb:'1345633',
        cdetail:{
            name:'dev',
            email:'dev@dev.dev',
            telephone:'7777777777',
            city:'sikar',
            state:'raj',
            zip:'332301',
            address:'zootopia',
        },
        rdetail:{
            name:'rev',
            email:'dev@dev.dev',
            telephone:'7777777777',
            city:'rikar',
            state:'raj',
            zip:'332301',
            address:'xootopia',
        },
        package:{
            length:'10',
            breadth:'10',
            height:'10',
            weight:'10',
            mode:'express'
        }
    },
]